[versions]
agp = "8.1.1"
androidxCore = "1.9.0"
androidxAppCompat = "1.6.1"
androidxDataStore = "1.0.0"
androidxNavigation = "2.5.3"
kotlin = "1.9.0"

material = "1.9.0"

hilt = "2.48"
javaInject = "1"

gms = "20.7.0"

junit = "4.13.2"
kotest = "5.8.0"
mockk = "1.13.8"

retrofit = "2.9.0"
okhttp = "4.11.0"
kotlinx-serialization = "1.6.0"
kotlinx-serialization-converter = "1.0.0"
coroutines = "1.3.5"

glide = "4.15.0"
timber = "5.0.1"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDataStore" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaInject" }

google-play-services = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "gms" }

kotest-runner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest"}
kotest-property = { group = "io.kotest", name = "kotest-property", version.ref = "kotest"}
kotest-extentions-junitxml = { group = "io.kotest", name = "kotest-extensions-junitxml", version.ref = "kotest"}
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk"}

retrofit = { module = "com.squareup.retrofit2:retrofit", name = "retrofit", version.ref = "retrofit" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", name = "okhttp", version.ref = "okhttp" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlinx-serialization-converter" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
navigation-safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidxNavigation" }